[check]
cmd = [
  "nix",
  "flake",
  "check",
  "--override-input",
  "namaka",
  "github:nix-community/namaka",
]

[eval]
cmd = [
  "nix",
  "eval",
  "./#checks",
  "--override-input",
  "namaka",
  "github:nix-community/namaka",
]
